version: '3.3'
services:
  api:
    container_name: 'api'
    build: './api'
    ports:
      - '8080:8080'
    volumes:
      - './api:/go/src/app'
    depends_on:
      - 'mongo'

  frontend: 
    container_name: 'frontend'
    build: './frontend'
    volumes:
      - './frontend:/react-app'
    depends_on:
      - 'api'
    ports:
      - "3000:3000"

  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    
